title: yoosangbird's Homepage
page-top-title: yoosangbird
top-section-bg-text: Be what you wanna be
home-subtitle: yoosangbird&ensp;|&ensp;尹涵晨
copyright-text: '&copy; yoosangbird 2023-2025. All Rights Reserved.'
